remote_theme: just-the-docs/just-the-docs
title: Finance et Economie
description: Finance et Economie
# Navigation automatique bas√©e sur la structure de fichiers
aux_links:
  "GitHub": "https://github.com/nuagerouge00/finance"

