remote_theme: just-the-docs/just-the-docs
title: Finance et Economie
description: Finance et Economie
# Navigation automatique basée sur la structure de fichiers
aux_links:
  "GitHub": "https://github.com/nuagerouge00/finance"

# Ajouter du CSS personnalisé
heading_anchors: true
